spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: ourmusic
#spring.data.mongodb.authentication-database=
#spring.data.mongodb.username=
#spring.data.mongodb.password=

server:
  port: 8091
  servlet:
    context-path:
    session:
      cookie:
        name: UISESSION

security:
  oauth2:
    client:
      client-id: SampleClientId
      client-secret: my-secret
#      access-token-uri: http://localhost:8091/auth/oauth/token
      access-token-uri: http://5d026ac3f8d4.eu.ngrok.io/auth/oauth/token
#      user-authorization-uri: http://localhost:8091/auth/oauth/authorize
      user-authorization-uri: http://5d026ac3f8d4.eu.ngrok.io/auth/oauth/authorize
    resource:
      user-info-uri: http://localhost:8091/auth/user/me

spotify:
  client-id: 3bb1371bd1b748269233273ce39229c3
  client-secret: f9e20d71dc45472782976c4fd6c1c8a2
  callback-uri: http://448aac935426.eu.ngrok.io/spotify/auth/redirect
#  callback-uri: http://localhost:4200/spotify/auth/redirect
  scope: user-modify-playback-state,user-read-currently-playing,user-read-playback-state