spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: ourmusic
#spring.data.mongodb.authentication-database=
#spring.data.mongodb.username=
#spring.data.mongodb.password=

server:
  port: 8091
  servlet:
    context-path:
    session:
      cookie:
        name: UISESSION

security:
  oauth2:
    client:
      client-id: SampleClientId
      client-secret: my-secret
      access-token-uri: http://localhost:8091/auth/oauth/token
      user-authorization-uri: http://localhost:8091/auth/oauth/authorize
    resource:
      user-info-uri: http://localhost:8091/auth/user/me